name: wp-lando-app
recipe: pantheon
services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_10.x | bash
      - apt install -y nodejs
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update && apt-get install --no-install-recommends yarn
    build:
      - cd /app && composer install -n
    run_as_root:
      - npm install --global yarn
  node:
    type: node
tooling:
  yarn:
    service: appserver
config:
  cache: false
